module.exports =  {
    scriptConsultaHoraCreacionTemporalPassword: "SELECT userTempPasswordChangeTimestamp FROM usertemppasswordchange WHERE userId= ? and usertemppasswordchangeValue=?;",
    scriptUpdatePassword: "UPDATE `users` SET `userPassword` = ? WHERE (`userId` = ?);",
    scriptGetUserIdFromUserEmail: "SELECT userId FROM users WHERE userEmail = ? limit 1;",
    scriptCreateTemporalPassword: "INSERT INTO usertemppasswordchange (userTempPasswordChangeTimestamp,userTempPasswordChangeValue,userId) VALUES (NOW(), ?,?);",
    scriptVerifyUserPassword: "SELECT userId FROM users WHERE userEmail = ? and userPassword = ? limit 1",
    scriptCreateUser: "INSERT INTO `users` (`userName`, `userEmail`, `userPassword`, `userPhoneNumber`, `userNationalId`, `userNationality`, `userPrefixNational`, `userDateOfBirth`, `userMoney`, `userDateOfRegister`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 0, NOW());",
    scriptCheckEmailRegistered: "SELECT count(userId) as cantidad FROM users where userEmail = ?;",
    scriptInsertJobOffer: "INSERT INTO `joboffers` (`userId`, `jobOfferDescription`, `jobOfferDateAtCreate`, `jobOfferDateAtWork`, `jobOfferEstimatePrice`, `jobOfferTittle`) VALUES (?, ?, NOW(), ?, ?, ?);",
    scriptGetLaborCategories: "SELECT laborCategoryId, laborCategoryName FROM easyfixy.laborcategories;",
    scriptModifyUserInfo: "UPDATE `users` SET `userPhoneNumber` = ?, `userNationality` = ?, `userPrefixNational` = ? WHERE (`userId` = ?);",
    scriptInsertResume: "INSERT INTO `resumes` (`userId`, `resumeDescription`, `resumeTimeExperience`, `resumeTitleLabor`) VALUES (?, ?, ?, ?);",
    scriptInsertLaborResumeRelationship: "INSERT INTO `laborsresumes` (`resumeId`, `laborId`) VALUES (?, ?);",
    scriptInsertUserSkill: "INSERT INTO `skills` (`userId`, `skillName`) VALUES (?, ?);",
    scriptGetUserMainData: "SELECT userName, userPhoneNumber, userNationalId, userEmail, userNationality, userPrefixNational, TIMESTAMPDIFF(YEAR, userDateOfBirth, CURDATE()) AS edad, TIMESTAMPDIFF(YEAR, userDateOfRegister, CURDATE()) AS 'antiguedadYears', TIMESTAMPDIFF(MONTH, userDateOfRegister, CURDATE()) % 12 AS 'antiguedadMonths' FROM users where userId=?;",
    scriptGetUserSkills: "SELECT skillId, skillName FROM skills where userId = ?;",
    scriptGetUserResumes: "SELECT resumeId, resumeDescription, resumeTimeExperience, resumeTitleLabor FROM resumes where userId = ?;",
    scriptGetResumeLebors: "SELECT l.laborId, b.laborCategoryId, b.laborName FROM laborsresumes as l join resumes as r on r.resumeId = l.resumeId join labors as b on b.laborId = l.laborId where l.resumeId=?;",
    scriptUpdateUserTempDataActivate: "UPDATE `userstempdata` SET `userTempDataLatitude` = ?, `userTempDataLongitude` = ?, `userTempDataActive` = '1', `userTempDataDate` = NOW() WHERE (`userTempDataId` = ?);",
    scriptUpdateUserTempDataDeactivate: "UPDATE `easyfixy`.`userstempdata` SET `userTempDataActive` = '0', `userTempDataDate` = NOW() WHERE (`userTempDataId` = ?);"
}